version: "2"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "7700:3000"
    links:
      - db
    command: npm start
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql
    #ports:
    #  - "7706:3306"
